<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.12.0.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="/js/apihome.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/manage/apihome">API管理平台</a>
        </div>
    </div>
</nav>

<div class="container">
    <form class="form-inline">
        <div class="form-group">
            <label for="search_id">ID：</label>
            <input type="text" class="form-control" id="search_id">
        </div>
        <div class="form-group">
            <label for="search_project">所属项目：</label>
            <input type="text" class="form-control" id="search_project">
        </div>
        <button type="button" class="btn btn-primary" id="search_btn">查询</button>
        <button type="button" class="btn btn-primary" id="add">添加</button>
    </form>
    <br/>
    <table class="table table-striped" style="word-break:break-all; word-wrap: break-word;">
        <thead>
        <tr>
            <th>id</th>
            <th>所属项目</th>
            <th>接口地址</th>
            <th>接口键值</th>
            <th>请求报文</th>
            <th>期待结果</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <?php
        foreach ($result as $item) { ?>
            <tr>
                <td><?= $item['id'] ?></td>
                <td><?= $item['project'] ?></td>
                <td><?= $item['path'] ?></td>
                <td><?= $item['key'] ?></td>
                <td><?= $item['params'] ?></td>
                <td><?= $item['expect'] ?></td>
                <td>
                    <a href="#">编辑</a>
                    <a href="#">删除</a>
                </td>
            </tr>
        <?php }
        ?>
        </tbody>
    </table>

    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">添加</h4>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="project">所属项目：</label>
                            <input type="text" id="project">
                        </div>
                        <div class="form-group">
                            <label for="url">接口地址：</label>
                            <input type="text" id="url">
                        </div>
                        <div class="form-group">
                            <label for="key">接口键值：</label>
                            <input type="text" id="key">
                        </div>
                        <div class="form-group">
                            <label for="params">请求报文：</label>
                            <input type="text" id="params">
                        </div>
                        <div class="form-group">
                            <label for="expect">期待结果：</label>
                            <input type="text" id="expect">
                        </div>
                    </form>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">保存</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                </div>
            </div>

        </div>
    </div>
</div>

</body>
</html>