<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>linkQC</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.12.0.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="/js/linkqc.js"></script>
</head>
<body>

<div class="container">

    <strong><h4>模拟Link生成二维码</h4></strong>
    <hr>
    <form class="form-horizontal" role="form" target="_blank" id="ehomePaySubmit" name="ehomePaySubmit"
          action="http://10.12.9.23:8083/poscashier_web/payByOrderPos/index" method="post">
        <div class="form-group">
            <label class="control-label col-sm-2" for="prodCatalog">prodCatalog:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="prodCatalog" name="prodCatalog" value="02">
            </div>


            <label class="control-label col-sm-2" for="subject">subject:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="subject" name="subject" value="租赁合同[100000354497]佣金收款">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="input_charset">input_charset:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="input_charset" name="input_charset" value="utf-8">
            </div>

            <label class="control-label col-sm-2" for="notify_url">notify_url:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="notify_url" name="notify_url"
                       value="http://10.12.9.23:8083/poscashier_web/payByOrderPos/callback.do">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="orderTime">orderTime:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="orderTime" name="orderTime" value="<?= $time ?>">
            </div>

            <label class="control-label col-sm-2" for="partnerFlow">partnerFlow:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="partnerFlow" name="partnerFlow" value="71">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="operator">operator:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="operator" name="operator" value="1000000020043722">
            </div>

            <label class="control-label col-sm-2" for="currency">currency:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="currency" name="currency" value="01">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="orderNo">orderNo:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="orderNo" name="orderNo" value="71">
            </div>

            <label class="control-label col-sm-2" for="totalAmount">totalAmount:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="totalAmount" name="totalAmount" value="0.01">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="service">service:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="service" name="service" value="ehomePayByOrder">
            </div>

            <label class="control-label col-sm-2" for="seller_id">seller_id:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="seller_id" name="seller_id"
                       value="tianjin01@homelink.com.cn">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="partner">partner:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="partner" name="partner" value="20150714100100000001">
            </div>

            <label class="control-label col-sm-2" for="extend_params">extend_params:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="extend_params" name="extend_params"
                       value="{'contractNo':'100000354497'}">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="sign_key">sign_key:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="sign_key" value="seNJ00">
            </div>

            <label class="control-label col-sm-2" for="sign_value">sign_type:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" name="sign_type" value="MD5">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="sign_value">sign_value:</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="sign_value" name="sign">
            </div>

            <label class="control-label col-sm-2">select:</label>
            <div class="col-sm-4">
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">测试环境
                        <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                        <li><a href="#" id="test_env">测试环境</a></li>
                        <li><a href="#" id="huidu_env">灰度环境</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-4">
                <button type="button" class="btn btn-primary" id="sign_btn">生成验签值</button>
                <button type="submit" class="btn btn-primary">提交</button>
                <a type="button" class="btn btn-primary" href="http://10.35.13.45:8000/MockServer/mockhome">返回</a>
            </div>
        </div>
    </form>
</div>
</body>
</html>